### ISSUE TITLE
family の更新処理でエラー

### ISSUE THREAD

**Issue by albatrosary** [k-mopi/financial-plan#15]
http://financial-plan.azurewebsites.net/family

```
vendor.51692e8….bundle.js:526 ORIGINAL STACKTRACE:
t.handleError @ vendor.51692e8….bundle.js:526
next @ vendor.51692e8….bundle.js:302
e.object.o @ vendor.51692e8….bundle.js:533
e.__tryOrUnsub @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e._next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:176
e.emit @ vendor.51692e8….bundle.js:533
t.triggerError @ vendor.51692e8….bundle.js:239
onHandleError @ vendor.51692e8….bundle.js:239
t.handleError @ polyfills.d65471b….bundle.js:38
n.runTask @ polyfills.d65471b….bundle.js:38
invoke @ polyfills.d65471b….bundle.js:38
vendor.51692e8….bundle.js:526 TypeError: Cannot set property birthdayFormat of #<t> which has only a getter
    at e.handleEvent_9 (https://financial-plan.azurewebsites.net/1.0b52b70f8478b497a5e1.chunk.js:2:27794)
    at e.object.o [as _next] (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:169:865)
    at e.__tryOrUnsub (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:9258)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:8584)
    at e._next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:7668)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:7339)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:176:1273)
    at e.emit (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:169:331)
    at e.viewToModelUpdate (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:703:1596)
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:78:583
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8186
    at Array.forEach (native)
    at e.setValue (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8159)
    at e.reset (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8538)
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:10977
t.handleError @ vendor.51692e8….bundle.js:526
next @ vendor.51692e8….bundle.js:302
e.object.o @ vendor.51692e8….bundle.js:533
e.__tryOrUnsub @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e._next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:176
e.emit @ vendor.51692e8….bundle.js:533
t.triggerError @ vendor.51692e8….bundle.js:239
onHandleError @ vendor.51692e8….bundle.js:239
t.handleError @ polyfills.d65471b….bundle.js:38
n.runTask @ polyfills.d65471b….bundle.js:38
invoke @ polyfills.d65471b….bundle.js:38
vendor.51692e8….bundle.js:15 Uncaught TypeError: Cannot set property birthdayFormat of #<t> which has only a getter
    at e.handleEvent_9 (https://financial-plan.azurewebsites.net/1.0b52b70f8478b497a5e1.chunk.js:2:27794)
    at e.object.o [as _next] (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:169:865)
    at e.__tryOrUnsub (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:9258)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:8584)
    at e._next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:7668)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:15:7339)
    at e.next (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:176:1273)
    at e.emit (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:169:331)
    at e.viewToModelUpdate (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:703:1596)
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:78:583
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8186
    at Array.forEach (native)
    at e.setValue (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8159)
    at e.reset (https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:8538)
    at https://financial-plan.azurewebsites.net/vendor.51692e847d83fceb0012.bundle.js:596:10977
e.handleEvent_9 @ 1.0b52b70….chunk.js:2
e.object.o @ vendor.51692e8….bundle.js:169
e.__tryOrUnsub @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e._next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:176
e.emit @ vendor.51692e8….bundle.js:169
e.viewToModelUpdate @ vendor.51692e8….bundle.js:703
(anonymous) @ vendor.51692e8….bundle.js:78
(anonymous) @ vendor.51692e8….bundle.js:596
e.setValue @ vendor.51692e8….bundle.js:596
e.reset @ vendor.51692e8….bundle.js:596
(anonymous) @ vendor.51692e8….bundle.js:596
(anonymous) @ vendor.51692e8….bundle.js:596
e._forEachChild @ vendor.51692e8….bundle.js:596
e.reset @ vendor.51692e8….bundle.js:596
t.reset @ vendor.51692e8….bundle.js:892
t.onSubmit @ 1.0b52b70….chunk.js:1
e.handleEvent_0 @ 1.0b52b70….chunk.js:2
e.object.o @ vendor.51692e8….bundle.js:169
e.__tryOrUnsub @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e._next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:15
e.next @ vendor.51692e8….bundle.js:176
e.emit @ vendor.51692e8….bundle.js:169
e.onSubmit @ vendor.51692e8….bundle.js:274
t.handleEvent @ 1.0b52b70….chunk.js:1
e.handleEvent_0 @ 1.0b52b70….chunk.js:2
(anonymous) @ vendor.51692e8….bundle.js:386
t.invokeTask @ polyfills.d65471b….bundle.js:38
onInvokeTask @ vendor.51692e8….bundle.js:239
t.invokeTask @ polyfills.d65471b….bundle.js:38
n.runTask @ polyfills.d65471b….bundle.js:38
invoke @ polyfills.d65471b….bundle.js:38
family:1 Form submission canceled because the form is not connected
```

サーバではエラーだがクライアント（開発環境）ではエラーにならない

**Comment by albatrosary** [comment]
双方向バインディングを定義しているときはメソッドに対してsetter、getterを用意しておく。今回はsetter のみの指定でいいので片方向に変更する

Template HTML
```html
<input type="date" name="birthday" [(ngModel)]=birthdayFormat required placeholder="birthday">
```

TypeScript
```typescript

  public onSubmit(form: NgForm): void {

    const human: Human = {
      name: form.value.name,
      relationship: form.value.relationship,
      birthday: new Date(form.value.birthday)
    };

    this.familyService.update(this.rownum, human);

    form.reset();
  }

  get birthdayFormat(){
    return this.birthday.toISOString().substring(0, 10);
  }
}
```

下記に変更した

```html
<input type="date" name="birthday" [ngModel]=birthdayFormat required placeholder="birthday">
```
